import streamlit as st
from utils_adjusted import load_csv, load_ratings

# Set up page
st.set_page_config(
    layout="wide",
    page_title="Movie Recommender Home",
    page_icon=":movie_camera:"
)

st.title("🎬 Welcome to the Movie Recommender System")

# Load data using utility functions
movies = load_csv()
ratings = load_ratings()

# Dataset KPIs
n_movies = ratings["movieId"].nunique()
n_users = ratings["userId"].nunique()
n_ratings = len(ratings)
avg_rating_per_user = round(ratings.groupby("userId")["rating"].count().mean(), 2)

# Display KPIs
st.markdown("## 📊 Dataset Overview")
kpi1, kpi2, kpi3, kpi4 = st.columns(4)
kpi1.metric("🎞️ Unique Movies", f"{n_movies:,}")
kpi2.metric("🧍‍♂️ Unique Users", f"{n_users:,}")
kpi3.metric("⭐ Total Ratings", f"{n_ratings:,}")
kpi4.metric("📈 Avg. # of Ratings per User", f"{avg_rating_per_user}")

# Sample data
st.markdown("### 🔍 Ratings Sample")
st.dataframe(ratings.head(10), use_container_width=True)

st.markdown("---")

# Model Descriptions
st.markdown("""
## 🤖 Models Used

### 🎞️ Item-Based Collaborative Filtering (LensKit)

This model finds movies similar to those you've liked.

- Uses precomputed **item-item similarity** from LensKit (trained offline).
- When you rate a movie, it recommends items that were rated similarly by other users.
- It doesn't predict exact ratings — instead, it ranks items based on their similarity to your liked movies.

---

### 🧍‍♂️ User-Based Collaborative Filtering (FAISS-accelerated)

This model recommends movies based on ratings from users most similar to you.

 For each movie **you haven’t rated**, the model:
  - Finds users who **have rated that movie**.
  - Compares them to you using **cosine similarity** over co-rated items.
  - Builds a **temporary FAISS index** just for those users.
  - Retrieves the **top 50 most similar users** for that movie.
  - Predicts a rating by **aggregating their ratings**, weighted by:
    - Their similarity to you
    - How many movies you both rated (overlap)

- To ensure reliability:
  - Only neighbors with **at least 3 shared ratings** are considered.
  - A movie is only recommended if **at least 15 neighbors** contribute to its score.

➡️ This means every movie is recommended based on a **fresh, dynamic group of similar users**, specific to that movie — for **efficient, personalized, and high-quality predictions**.

---

### 🧠 AI-Generated Insights (LLaMA 3 via Ollama)

After generating recommendations, this system can explain **why** each movie was suggested to you using natural language.

- The explanations are generated by the **LLaMA 3 model** running locally via **Ollama**.
- It considers the movies you've rated highly and the genres of recommended titles.
- It uses plain, friendly language to give you context like:
  > *"Since you enjoyed tense thrillers like Se7en, you may like Fight Club for its psychological depth and mystery."*

These summaries are available by clicking **“Summarize Insights”** after getting recommendations.

---

To try it all out, visit **Model Recommendation** from the sidebar 👈.
""")
